---
title: "hhs_data_cleaning"
author: "Mariano Viz"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(here)
library(writexl)
library(readxl)
library(janitor)
library(jsonlite)
library(data.world)
library(kableExtra)
library(knitr)

```




```{r}
## Read in data

# Sites
biomass_sites <- read_excel(here("data", "raw","Aggregated Data - For baseline biomass change.xlsx"), sheet = "MA - Biomass by year")

# HHS
fastfield <- read_csv(here("data", "raw", "hhs_fastfield.csv"))

kobo_1 <- read_excel(here("data", "raw", "hhs_kobo_mod_1.xlsx"))
kobo_1_fp <- read_csv(here("data", "raw", "hhs_fp.csv"))

kobo_2 <- read_excel(here("data", "raw", "hhs_kobo_mod_2.xlsx"))

dwapi::configure(auth_token = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyLWFuZC1yLXN0dWRpbzptYXJpYW5vdml6IiwiaXNzIjoiY2xpZW50OnItYW5kLXItc3R1ZGlvOmFnZW50Om1hcmlhbm92aXo6OjEyYzRkOTYzLTk0NDctNDg5Ni04ZmM0LTQ5YTM1ZWQ2MWQ0NSIsImlhdCI6MTcyODUwNTU0MCwicm9sZSI6WyJ1c2VyX2FwaV9hZG1pbiIsInVzZXJfYXBpX3JlYWQiLCJ1c2VyX2FwaV93cml0ZSJdLCJnZW5lcmFsLXB1cnBvc2UiOnRydWUsInNhbWwiOnt9fQ.MSVsDGnQK4y3WWiWYrDluIYsojOmmbrJC-PeFSgZY7qDq63pIobopiDTHcaCX8LG7pwuBC5HBQrO8Kk8ifahpQ")
sql_stmt <- qry_sql("SELECT * FROM hhs_fp_hnd")  
kobo_2_fp_hon <- data.world::query(
  sql_stmt, "rare/household-surveys"
)
kobo_2_fp_phi <- read_csv(here("data", "raw", "hhs_fp_phl.csv"))

#kobo_3 <- read_excel(here("data", "raw", "hhs_kobo_mod_3.xlsx")) #Check which sheets are relevant!
kobo_3_fp_ind <- read_csv(here("data", "raw", "hhs_fp_idn.csv"))

```





```{r}
# Get sites
sites <- biomass_sites %>%
  select(ma_name, country) %>%
  distinct()

sites_year <- biomass_sites %>%
  select(ma_name, country, year)
sites_year$ma_name <- tolower(gsub(" ", "_", sites_year$ma_name))
```





```{r}
# Initial explorations of fastfield/kobo dfs

# Check structure
str(fastfield)
str(kobo_1_fp)
str(kobo_2_fp_hon)
str(kobo_2_fp_phi)
str(kobo_3_fp_ind)

# View first few rows 
head(fastfield)
head(kobo_1_fp)
head(kobo_2_fp_hon)
head(kobo_2_fp_phi)
head(kobo_3_fp_ind)

# Get summary statistics
summary(fastfield)
summary(kobo_1_fp)
summary(kobo_2_fp_hon)
summary(kobo_2_fp_phi)
summary(kobo_3_fp_ind)


# Summary of the datasets that will be used
fastfield_summary <- data.frame(
  column_name = names(fastfield),
  possible_values = sapply(fastfield, function(x) paste(unique(x), collapse = ", ")),
  row.names = NULL
) #Key grouping variables: maa and year

kobo_1_fp_summary <- data.frame(
  column_name = names(kobo_1_fp),
  possible_values = sapply(kobo_1_fp, function(x) paste(unique(x), collapse = ", ")),
  row.names = NULL
) #Key grouping variables: ma_name and submission_time

kobo_2_fp_hon_summary <- data.frame(
  column_name = names(kobo_2_fp_hon),
  possible_values = sapply(kobo_2_fp_hon, function(x) paste(unique(x), collapse = ", ")),
  row.names = NULL
) #Key grouping variables: ma_name and submission_time

kobo_2_fp_phi_summary <- data.frame(
  column_name = names(kobo_2_fp_phi),
  possible_values = sapply(kobo_2_fp_phi, function(x) paste(unique(x), collapse = ", ")),
  row.names = NULL
) #Key grouping variables:level4_name -ONLY Palawan (Province)- and submission_time (2024)

kobo_3_fp_ind_summary <- data.frame(
  column_name = names(kobo_3_fp_ind),
  possible_values = sapply(kobo_3_fp_ind, function(x) paste(unique(x), collapse = ", ")),
  row.names = NULL
) #Key grouping variables: ma_name (3 sites) and submission_time


```




```{r}
# Check sites on fastfield df

# Convert all sites to ma_name and to snake case lowercase
sites$ma_name <- tolower(gsub(" ", "_", sites$ma_name))

fastfield$ma_name <- tolower(gsub(" ", "_", fastfield$maa))
kobo_1_fp$ma_name <- tolower(gsub(" ", "_", kobo_1_fp$ma_name))
kobo_2_fp_hon$ma_name <- tolower(gsub(" ", "_", kobo_2_fp_hon$ma_name))
kobo_2_fp_phi$level4_name <- tolower(gsub(" ", "_", kobo_2_fp_phi$level4_name))
kobo_3_fp_ind$ma_name <- tolower(gsub(" ", "_", kobo_3_fp_ind$ma_name))


# Filtered dfs
fastfield_filtered <- fastfield %>%
  select(ma_name, year) %>% 
  filter(ma_name %in% sites$ma_name)

kobo_1_fp$year <- year(ymd(kobo_1_fp$submission_time))  
kobo_1_fp_filtered <- kobo_1_fp %>%
  select(ma_name, submission_time, year) %>% 
  filter(ma_name %in% sites$ma_name)

kobo_2_fp_hon$year <- year(ymd(kobo_2_fp_hon$submission_time))
kobo_2_fp_hon_filtered <- kobo_2_fp_hon  %>%
  select(ma_name, submission_time, year) %>% 
  filter(ma_name %in% sites$ma_name)

kobo_2_fp_phi$year <- year(ymd(kobo_2_fp_phi$submission_time))
kobo_2_fp_phi_filtered <- kobo_2_fp_phi %>%
  select(ma_name, submission_time, year) %>% 
  filter(ma_name %in% sites$ma_name)

kobo_3_fp_ind$year <- year(ymd(kobo_3_fp_ind$submission_time))
kobo_3_fp_ind_filtered <- kobo_3_fp_ind %>%
  select(ma_name, submission_time, year) %>% 
  filter(ma_name %in% sites$ma_name)


```




```{r}
# Viz

combined_data <- rbind(
  fastfield_filtered %>% select(ma_name, year),
  kobo_1_fp_filtered %>% select(ma_name, year),
  kobo_2_fp_hon_filtered %>% select(ma_name, year),
  kobo_2_fp_phi_filtered %>% select(ma_name, year),
  kobo_3_fp_ind_filtered %>% select(ma_name, year)
)

survey_count <- combined_data %>%
  group_by(ma_name, year) %>%
  summarize(survey_count = n())


ggplot(survey_count, aes(x = year, y = survey_count, group = ma_name, color = ma_name)) +
  geom_line() +    # Plot lines for each reserve
  geom_point() +   # Add points to show the exact count
  labs(title = "Number of Surveys per Year for Each Marine Reserve",
       x = "Year",
       y = "Number of Surveys",
       color = "Marine Reserve") +
  theme_minimal()


ggplot(survey_count, aes(x = year, y = survey_count)) +
  geom_line() +    # Plot lines for each reserve
  geom_point() +   # Add points to show the exact count
  labs(title = "Number of Surveys per Year for Each Marine Reserve",
       x = "Year",
       y = "Number of Surveys") +
  facet_wrap(~ ma_name) +
  theme_minimal()

ggplot(survey_count, aes(x = year, y = survey_count, color = ma_name)) +
  geom_point(size = 3) +  # Add points, adjust size as needed
  labs(title = "Number of Surveys per Year for Each Marine Reserve",
       x = "Year",
       y = "Number of Surveys",
       color = "Marine Reserve") +
  theme_minimal()



combined_data_fw <- rbind(
  fastfield_filtered %>% select(ma_name, year) %>% mutate(dataset = "Fastfield"),
  kobo_1_fp_filtered %>% select(ma_name, year) %>% mutate(dataset = "Kobo 1"),
  kobo_2_fp_hon_filtered %>% select(ma_name, year) %>% mutate(dataset = "Kobo 2"),
  kobo_2_fp_phi_filtered %>% select(ma_name, year) %>% mutate(dataset = "Kobo 2"),
  kobo_3_fp_ind_filtered %>% select(ma_name, year) %>% mutate(dataset = "Kobo 3")
)

survey_count_fw <- combined_data_fw %>%
  group_by(ma_name, year, dataset) %>%
  summarize(survey_count = n())

hhs_year_source <- ggplot(survey_count_fw, aes(x = year, y = survey_count, color = dataset)) +
  geom_point(size = 3) +   # Add points for each survey count
  labs(title = "HHS by Year for Each Marine Reserve",
       x = "Year",
       y = "Number of Surveys",
       color = "HHS Source") +  # Color by dataset source
  facet_wrap(~ ma_name) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



```{r}

# Tables 
survey_summary <- survey_count %>%
  group_by(ma_name) %>%
  summarize(
    survey_periods = paste(unique(year), collapse = ", "),  # List the unique survey years
    total_surveys = sum(survey_count)  # Sum the total number of surveys
  )

missing_ma_names <- sites$ma_name[!sites$ma_name %in% survey_summary$ma_name]

missing_summary <- data.frame(
  ma_name = missing_ma_names,
  survey_periods = "0",  
  total_surveys = 0     
)

full_survey_summary <- rbind(survey_summary, missing_summary) %>%
  arrange(desc(total_surveys))

# Group by ma_name and put years into a single string
sites_year_biomass <- sites_year %>%
  group_by(ma_name) %>%
  summarize(biomass_survey = paste(unique(year), collapse = ", "),
            country = first(country)) 

# Merge the two datasets based on ma_name
hhs_biomass_data <- full_survey_summary %>%
  left_join(sites_year_biomass, by = "ma_name") %>%
  rename(hh_survey = survey_periods,
         total_hh_survey = total_surveys) %>%
  select(ma_name, country, biomass_survey, hh_survey, total_hh_survey)


hhs_biomass_long <- hhs_biomass_data %>%
  filter(hh_survey != "0") %>%  # Remove rows where hh_survey is "0"
  separate_rows(biomass_survey, sep = ", ") %>% 
  mutate(biomass_survey = as.integer(biomass_survey)) %>%
  separate_rows(hh_survey, sep = ", ") %>%
  mutate(hh_survey = as.integer(hh_survey)) %>%
  pivot_longer(cols = c(biomass_survey, hh_survey), 
               names_to = "survey_type", 
               values_to = "year") %>%
  filter(!is.na(year))


biomass_hhs_table <- hhs_biomass_data %>%
  kbl(caption = "Biomass and Household Survey Data Summary") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F)

ggplot(hhs_biomass_long, aes(x = year, y = ma_name, color = survey_type)) +
  geom_point(size = 2, alpha = 0.5) +  # Add points to indicate the survey year
  labs(title = "Biomass and Household Surveys per Marine Area",
       x = "Year",
       y = "Marine Reserve",
       color = "Survey Type") +
  scale_color_manual(values = c("biomass_survey" = "dodgerblue1", "hh_survey" = "orange1")) +
  scale_x_continuous(breaks = seq(2010, 2023, by = 1), limits = c(2010, 2023)) +  # Set breaks and limits for x-axis
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


biomass_hhs_plot <- ggplot(hhs_biomass_long, aes(x = year, y = survey_type, group = survey_type, color = survey_type)) +
  geom_line(size = 1, alpha = 0.5) +  # Add translucent lines connecting the points
  geom_point(size = 1) +  # Smaller points
  labs(title = "Biomass and Household Surveys per Marine Area",
       x = "Year",
       y = "Survey Type",
       color = "Survey Type") +
  scale_color_manual(values = c("biomass_survey" = "dodgerblue1", "hh_survey" = "orange1")) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2010, 2023, by = 3), limits = c(2010, 2023)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
        strip.text = element_text(size = 8)) +  # Adjust the size of facet labels
  facet_wrap(~ ma_name, scales = "free_y")

```






```{r}

biomass_hhs_table

hhs_year_source

biomass_hhs_plot


```

